---
name: actionlint
on:
  push:
    branches: [main]
    paths:
    - .github/**/*.yaml
  pull_request:
    branches: [main]
    paths:
    - .github/**/*.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: aquaproj/aqua-installer@v2.3.0
      with:
        aqua_version: v2.22.0
    - run: actionlint
