---
name: actionlint
on:
  push:
    branches: [main]
    paths:
    - .github/**/*.yaml
  pull_request:
    branches: [main]
    paths:
    - .github/**/*.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aquaproj/aqua-installer@v2.1.1
      with:
        aqua_version: v2.4.1
    - run: actionlint
