---
name: actionlint
on:
  push:
    branches: [main]
    paths:
    - .github/**/*.yaml
  pull_request:
    branches: [main]
    paths:
    - .github/**/*.yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: aquaproj/aqua-installer@v1.1.2
      with:
        aqua_version: v1.22.0
    - run: actionlint
