name: renovate-config-validator

on:
  pull_request:
    branches:
    - main
    paths:
    - .github/workflows/renovate-config-validator.yaml
    - renovate.json5
  push:
    branches:
    - main
    paths:
    - .github/workflows/renovate-config-validator.yaml
    - renovate.json5

jobs:
  validate:
    timeout-minutes: 30
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false
    - uses: suzuki-shunsuke/github-action-renovate-config-validator@ca480cb7ec89a9e1cd8c214ad33bda1617184027 # v2.0.0
